spring.application.name=sm-health-core

# Server Configuration
server.port=8080

# MariaDB Database Configuration
spring.datasource.url=jdbc:mariadb://94.46.180.24:3306/${DB_NAME:sm_health_core}
spring.datasource.driverClassName=org.mariadb.jdbc.Driver
spring.datasource.username=nfoliveira
spring.datasource.password=oliveiraDB2024#
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# JPA Settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
